disconnect automatically when no user in voice
aria-music/zundacord pull request #53
Opened 2023-05-08 17:02 UTC by mnsinri

resolve #21 

**未対応**
ずんだもんをvcから切断すると[Reconnect処理](https://github.com/aria-music/zundacord/blob/main/src/zundacord/app.ts#L263)がはしる。
この時に`/join`すると、ずんだもんがvcにいないのにAlready joined!と表示される。

2023-05-09 14:45 UTC, sarisia commented
> 未対応
> ずんだもんをvcから切断するとReconnect処理がはしる。
> この時に/joinすると、ずんだもんがvcにいないのにAlready joined!と表示される。

これは正常な仕様で、エラーなどでbotがサーバから切断された場合は自動で再接続が入るので /join できなくても5秒以内に戻ってくれるしいいだろうと思ってます。

（公式ガイドのワークアラウンドをそのまま実装してます。いい方法があったら教えて欲しい）

https://discordjs.guide/voice/voice-connections.html#handling-disconnects

2023-05-10 14:33 UTC, sarisia commented on src/zundacord/app.ts
> +const TIMEOUT = 5000 //ms
rename this to `AUTO_DISCONNECT_TIMEOUT`

2023-05-10 14:37 UTC, sarisia commented on src/zundacord/app.ts
> +    onVoiceStateUpdate(oldState: VoiceState, newState: VoiceState)
use `newState`, not `oldState` maybe?

2023-05-10 14:48 UTC, sarisia requested changes
以前に `clearTimeout` はサーバ単位で複雑だからいらないと言ってしまったけど, やっぱ必要そう. すみません.

`class Player` がサーバ単位で管理されているので, auto disconnect 機能をこっちに移しつつ, 1サーバにつき auto disconnect タイマーが1つしか走らないように変更してもらえると嬉しいです

2023-05-11 17:05 UTC, sarisia requested changes

2023-05-11 17:05 UTC, sarisia commented on src/zundacord/player.ts
> +        clearTimeout(this.disconnectTimeoutId)
これやった後の `this.disconnectTimeoutId` のクリアを忘れているけど https://github.com/aria-music/zundacord/pull/53#discussion_r1191459581 を解決すれば一緒に直りそう

2023-05-11 17:24 UTC, mnsinri commented on src/zundacord/app.ts
> +        player.autoDisconnect(vc, channel, this.applicationId, AUTO_DISCONNECT_TIMEOUT);
#58 でやろうと思ってました

2023-05-11 17:24 UTC, sarisia commented on src/zundacord/app.ts
> +        player.autoDisconnect(vc, channel, this.applicationId, AUTO_DISCONNECT_TIMEOUT);
それでもいいよ

2023-05-11 18:12 UTC, sarisia approved these changes

2023-05-11 18:12 UTC, merged