Feature add purge command
aria-music/zundacord pull request #55
Opened 2023-05-09 16:03 UTC by ma1750

Resolved #52 

コマンド名は`/purge`にしました．
![image](https://github.com/aria-music/zundacord/assets/43315739/703676d4-15da-4a24-b580-c3a2faacd232)

2023-05-10 14:06 UTC, sarisia requested changes
/disconnect でお願いします！後出しでごめん

2023-05-10 14:16 UTC, ma1750 commented
`/disconnect` に変更しました．

2023-05-10 14:29 UTC, sarisia requested changes

2023-05-11 16:40 UTC, sarisia commented on src/zundacord/app.ts
> +            }
大丈夫そうなら resolve してほしい

2023-05-11 16:45 UTC, sarisia approved these changes

2023-05-11 16:52 UTC, merged